version: '3'
services:

  mysql:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3308:3308
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel_app
      - LANG=C.UTF-8

  app:
    build: ./php
    volumes:
      - ./src:/var/www/src
      - ./php/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - 8088:80
    depends_on:
      - mysql
volumes:
  mysql:
